#!/usr/bin/env bash
[[ " help tar:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | tar:help)
    help_content='    tar:in <app>, Reads an tarball containing the app from stdin
    tar:from <app> <url>, Loads an app tarball from url.'
    if [[ $1 = "tar:help" ]] ; then
        echo -e 'Usage: dokku tar[:COMMAND]\n\nAn alternative to using git, apps are loaded via tarballs instead.\n\nAdditional commands:'
        echo "$help_content" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
