#!/usr/bin/env bash
[[ " help domains:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | domains:help)
    help_content='    domains [<app>], List domains
    domains:add <app> DOMAIN, Add a domain to app
    domains:clear <app>, Clear all domains for app
    domains:disable <app>, Disable VHOST support
    domains:enable <app>, Enable VHOST support
    domains:remove <app> DOMAIN, Remove a domain from app
    domains:set-global <domain>, Set global domain name'
    if [[ $1 = "domains:help" ]] ; then
        echo -e 'Usage: dokku domains[:COMMAND]\n\nManage vhost domains used by the Dokku proxy.\n\nAdditional commands:'
        echo "$help_content" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
