#!/usr/bin/env bash
[[ " help shell:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | shell:help)
    help_content='    shell, Spawn dokku shell'
    if [[ $1 = "shell:help" ]] ; then
        echo -e 'Usage: dokku docker-options[:COMMAND]\n\nDokku shell is an interactive dokku prompt.\n\nNote: See dokku enter:help for shell access to containers.\n\nAdditional commands:'
        echo "$help_content" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
