#!/usr/bin/env bash
[[ " help docker-options:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | docker-options:help)
    help_content='    docker-options <app> [phase(s)], Display app'"'"'s Docker options for all phases (or comma separated phase list)
    docker-options:add <app> <phase(s)> OPTION, Add Docker option to app for phase (comma separated phase list)
    docker-options:remove <app> <phase(s)> OPTION, Remove Docker option from app for phase (comma separated phase list)'
    if [[ $1 = "docker-options:help" ]] ; then
        echo -e 'Usage: dokku docker-options[:COMMAND]\n\nDisplay app'"'"'s Docker options for all phases.\n\nAdditional commands:'
        echo "$help_content" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
  ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
  ;;

esac
