#!/usr/bin/env bash
[[ " help enter:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | enter:help)
    help_content='    enter <app> [<container-type> || --container-id <container-id>], Connect to a specific app container'
    if [[ $1 = "enter:help" ]] ; then
        echo -e 'Usage: dokku enter <app>\n\nAllows you to access a bash prompt inside the container of the app.\n\nAdditional commands:'
        echo "$help_content" | sort | column -c2 -t -s,
    else
        echo "$help_content"
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
